<a href="https://colab.research.google.com/github/Shatoll/Logica-de-Programacao/blob/main/Practice_Introduction_to_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
print("6" * (2 **2))
# A multiplicação de "6" (string) por 4 (2^2) resulta em "6666". Portanto, não há multiplicação numérica.

6666


In [9]:
x = [-1, -2]
del(x[0])
# A função del() deletará o elemento selecionado da lista referida. A sequência de elementos inicia em 0. Neste caso, deletou o primeiro elemento (-1) da lista x.
print(x[0])

x =[-1, -3, 17]
del(x[0])
print(x[1])
# O primeiro elemento (-1) foi deletado. Em seguida, o segundo termo dos elementos restantes foi impresso.

-2
17


In [11]:
import math
# O módulo math dá acesso a funções matemáticas da linguagem de progrmação C.
print(math .pi + 4)
# Através do módulo math, é possível identificar a variável pi (3.14159...).

7.141592653589793


In [19]:
import numpy
# O módulo numpy possibilita operações metemáticas como arranjos, matrizes, etc.
n = numpy.array([1, 2, 3])
# Deve-se referenciar a função como módulo.função().
print(n)

import numpy as np
# Para evitar repetição, pode-se renomear o módulo por um nome menor através do comando "as".
m = np.array([2, 4, 6])
print(m)

from numpy import array
# Caso necessário, você é capaz de importar apenas uma função específica (array) de um módulo.
l = n * 3
# Realização da multiplicação do módulo "l" por 3.
print(l)

[1 2 3]
[2 4 6]
[3 6 9]
